import { useEffect, useMemo, useRef, useState } from 'react'
import { Alert, Box, Button, Chip, Divider, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import { LineChart } from '@mui/x-charts/LineChart'
import type { ResultTable, ResultsBundle, RunResults, SavedTraceData, SourceAmplitudeUnit } from '../types'
import { getJcoAdapter } from '../services/jcoAdapter'
import { sourceCoordinateLabel } from '../utils/resultUnits'
import { HeatmapGrid } from './HeatmapGrid'

type HbView = 'landscape' | 'response'
type ConvergenceFilter = 'all' | 'converged' | 'nonconverged'
type TraceComponent = 'values' | 'magnitude' | 'real' | 'imag' | 'phase'
type LoadedTrace = { key: string; trace: SavedTraceData; component: TraceComponent }
type TraceSelection = { key: string; component: TraceComponent }
type AxisSource = { key: string; trace: SavedTraceData } | null
type CatalogItem = { key: string; quantityKey: string; quantityName: string; arrayName: string; length: number }
type NumericRow = number[]
type HbGrid = { x: number[]; y: number[]; values: Array<Array<number | null>>; pointIds: Array<Array<number | null>> }
type PlotGroup = { key: string; x: number[]; xLabel: string; traces: LoadedTrace[] }

function rowsAsNumbers(table: ResultTable): NumericRow[] { return table.rows.map((row) => row.map(Number)) }
function unique(values: number[]): number[] { return [...new Set(values.filter(Number.isFinite))].sort((a, b) => a - b) }
function formatNumber(value: number | null | undefined): string { if (value == null || !Number.isFinite(Number(value))) return ''; const n = Number(value); if (n === 0) return '0'; const a = Math.abs(n); if (a < 1e-3 || a >= 1e4) return n.toExponential(4); return Number(n.toPrecision(6)).toString() }
function sourceCoordinateColumns(table: ResultTable) { return table.columns.filter((column) => /^source_\d+_(frequency|amplitude)$/i.test(column)) }
function amplitudeColumns(table: ResultTable) { return sourceCoordinateColumns(table).filter((column) => /_amplitude$/i.test(column)) }
function metricColumns(table: ResultTable) { const coords = new Set(sourceCoordinateColumns(table)); return table.columns.filter((column) => column !== 'point_id' && column !== 'converged' && !coords.has(column)) }
function columnValues(table: ResultTable, column: string) { const index = table.columns.indexOf(column); return index < 0 ? [] : unique(rowsAsNumbers(table).map((row) => row[index])) }
function rowMatchesFixed(table: ResultTable, row: NumericRow, fixed: Record<string, number>) { return Object.entries(fixed).every(([column, value]) => row[table.columns.indexOf(column)] === value) }
function convergenceMatches(table: ResultTable, row: NumericRow, filter: ConvergenceFilter) { if (filter === 'all') return true; const index = table.columns.indexOf('converged'); if (index < 0) return filter === 'converged'; return filter === 'converged' ? row[index] === 1 : row[index] !== 1 }
function traceLabel(trace: Pick<SavedTraceData, 'quantityName' | 'arrayName'>) { return trace.quantityName === trace.arrayName ? trace.quantityName : `${trace.quantityName} · ${trace.arrayName}` }
function traceValues(item: LoadedTrace) { if (item.component === 'magnitude') return item.trace.magnitude ?? []; if (item.component === 'real') return item.trace.real ?? []; if (item.component === 'imag') return item.trace.imag ?? []; if (item.component === 'phase') return item.trace.phaseRad ?? []; return item.trace.values ?? [] }
function axisValues(trace: SavedTraceData) { return trace.values ?? trace.magnitude ?? trace.real ?? [] }
function traceAxisKey(trace: SavedTraceData) { return `${trace.xKind}|${trace.x.length}|${trace.x[0] ?? 0}|${trace.x[trace.x.length - 1] ?? 0}` }

export function buildHbGrid(table: ResultTable, xName: string, yName: string, metricName: string, fixed: Record<string, number>, convergence: ConvergenceFilter): HbGrid {
  const xi = table.columns.indexOf(xName); const yi = table.columns.indexOf(yName); const mi = table.columns.indexOf(metricName); const pi = table.columns.indexOf('point_id')
  const rows = rowsAsNumbers(table).filter((row) => Number.isFinite(row[xi]) && Number.isFinite(row[yi]) && rowMatchesFixed(table, row, fixed) && convergenceMatches(table, row, convergence))
  const x = unique(rows.map((row) => row[xi])); const y = unique(rows.map((row) => row[yi])); const map = new Map(rows.map((row) => [`${row[xi]}|${row[yi]}`, row]))
  return { x, y, values: y.map((yv) => x.map((xv) => { const row = map.get(`${xv}|${yv}`); const value = row?.[mi]; return value != null && Number.isFinite(value) ? value : null })), pointIds: y.map((yv) => x.map((xv) => { const row = map.get(`${xv}|${yv}`); const id = pi >= 0 ? row?.[pi] : null; return id != null && Number.isFinite(id) ? id : null })) }
}

function plotGroups(traces: LoadedTrace[], xSource: AxisSource): PlotGroup[] {
  if (!traces.length) return []
  if (xSource) {
    const custom = axisValues(xSource.trace)
    const compatible = traces.filter((item) => traceValues(item).length === custom.length)
    const incompatible = traces.filter((item) => traceValues(item).length !== custom.length)
    const groups: PlotGroup[] = compatible.length ? [{ key: `custom:${xSource.key}`, x: custom, xLabel: traceLabel(xSource.trace), traces: compatible }] : []
    const byAxis = new Map<string, LoadedTrace[]>()
    incompatible.forEach((item) => { const key = traceAxisKey(item.trace); byAxis.set(key, [...(byAxis.get(key) ?? []), item]) })
    byAxis.forEach((items, key) => { const ref = items[0].trace; groups.push({ key, x: ref.xKind === 'frequency_hz' ? ref.x.map((value) => value / 1e9) : ref.x, xLabel: ref.xKind === 'frequency_hz' ? 'Frequency / GHz' : 'Index', traces: items }) })
    return groups
  }
  const byAxis = new Map<string, LoadedTrace[]>()
  traces.forEach((item) => { const key = traceAxisKey(item.trace); byAxis.set(key, [...(byAxis.get(key) ?? []), item]) })
  return [...byAxis.entries()].map(([key, items]) => { const ref = items[0].trace; return { key, x: ref.xKind === 'frequency_hz' ? ref.x.map((value) => value / 1e9) : ref.x, xLabel: ref.xKind === 'frequency_hz' ? 'Frequency / GHz' : 'Index', traces: items } })
}

function StoredConfigurations({ table, pointId, onSelect }: { table: ResultTable; pointId: number | null; onSelect: (id: number) => void }) {
  const pi = table.columns.indexOf('point_id')
  return <TableContainer sx={{ maxHeight: 300, border: '1px solid', borderColor: 'divider', borderRadius: 2 }}><Table stickyHeader size="small"><TableHead><TableRow>{table.columns.map((column) => <TableCell key={column}>{column}</TableCell>)}</TableRow></TableHead><TableBody>{table.rows.slice(0, 60).map((row, index) => { const id = pi >= 0 ? Number(row[pi]) : index + 1; return <TableRow key={id} hover selected={id === pointId} onClick={() => onSelect(id)} sx={{ cursor: 'pointer' }}>{row.map((value, ci) => { const n = Number(value); return <TableCell key={`${id}-${table.columns[ci]}`}>{Number.isFinite(n) ? formatNumber(n) : String(value)}</TableCell> })}</TableRow> })}</TableBody></Table></TableContainer>
}

function HbPointInspector({ run, table, pointId, amplitudeUnit }: { run: RunResults; table: ResultTable; pointId: number | null; amplitudeUnit: SourceAmplitudeUnit }) {
  const pi = table.columns.indexOf('point_id'); const row = pointId == null ? undefined : table.rows.find((candidate) => Number(candidate[pi]) === pointId); const savedPoint = pointId == null ? undefined : run.savedNonlinear?.points.find((point) => point.pointId === pointId)
  const [traces, setTraces] = useState<LoadedTrace[]>([]); const [xChoice, setXChoice] = useState('auto'); const [xSource, setXSource] = useState<AxisSource>(null); const [error, setError] = useState(''); const [loadingKey, setLoadingKey] = useState(''); const selectionRef = useRef<TraceSelection[]>([]); const xChoiceRef = useRef('auto')
  const catalog: CatalogItem[] = savedPoint?.quantities.flatMap((quantity) => quantity.arrays.map((array) => ({ key: `${quantity.name}/${array.name}`, quantityKey: quantity.name, quantityName: quantity.quantityName, arrayName: array.name, length: array.length }))) ?? []
  const readTrace = async (item: CatalogItem) => { const adapter = getJcoAdapter(); if (!adapter || pointId == null) throw new Error('Desktop result bridge is unavailable.'); return adapter.readSavedTrace({ runId: run.id, stage: 'nonlinear', pointId, quantityName: item.quantityKey, arrayName: item.arrayName }) }
  useEffect(() => { selectionRef.current = []; xChoiceRef.current = 'auto'; setTraces([]); setXChoice('auto'); setXSource(null); setError(''); setLoadingKey('') }, [run.id])
  useEffect(() => { if (pointId == null) return; let cancelled = false; const restore = async () => { if (!selectionRef.current.length && xChoiceRef.current === 'auto') return; setLoadingKey('point-change'); const next: LoadedTrace[] = []; for (const selection of selectionRef.current) { const item = catalog.find((candidate) => candidate.key === selection.key); if (!item) continue; try { const trace = await readTrace(item); next.push({ key: selection.key, trace, component: selection.component === 'values' && trace.magnitude ? 'magnitude' : selection.component }) } catch {} } if (cancelled) return; setTraces(next); const axisItem = catalog.find((item) => item.key === xChoiceRef.current); if (axisItem) try { setXSource({ key: axisItem.key, trace: next.find((item) => item.key === axisItem.key)?.trace ?? await readTrace(axisItem) }) } catch { setXChoice('auto'); setXSource(null) } else { setXChoice('auto'); setXSource(null) } setLoadingKey('') }; void restore(); return () => { cancelled = true } }, [pointId])
  const groups = useMemo(() => plotGroups(traces, xSource), [traces, xSource])
  if (!row || pointId == null) return <Alert severity="info">Select a configuration to inspect its source coordinates, device parameters, metrics and retained data.</Alert>
  const sourceCols = sourceCoordinateColumns(table); const metrics = metricColumns(table); const ci = table.columns.indexOf('converged')
  const addTrace = async (item: CatalogItem) => { if (selectionRef.current.some((s) => s.key === item.key)) return; setLoadingKey(item.key); setError(''); try { const trace = await readTrace(item); const component: TraceComponent = trace.magnitude ? 'magnitude' : 'values'; selectionRef.current = [...selectionRef.current, { key: item.key, component }]; setTraces((current) => [...current.filter((t) => t.key !== item.key), { key: item.key, trace, component }]) } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)) } finally { setLoadingKey('') } }
  const removeTrace = (key: string) => { selectionRef.current = selectionRef.current.filter((item) => item.key !== key); setTraces((current) => current.filter((item) => item.key !== key)); if (xChoiceRef.current === key) { xChoiceRef.current = 'auto'; setXChoice('auto'); setXSource(null) } }
  const chooseXAxis = async (choice: string) => { xChoiceRef.current = choice; setXChoice(choice); if (choice === 'auto') return setXSource(null); const item = catalog.find((candidate) => candidate.key === choice); if (!item) return; setLoadingKey(`x:${choice}`); try { setXSource({ key: choice, trace: traces.find((candidate) => candidate.key === choice)?.trace ?? await readTrace(item) }) } catch { setXChoice('auto'); setXSource(null) } finally { setLoadingKey('') } }
  return <Paper variant="outlined" sx={{ p: 1.7 }}><Stack spacing={1.5}>
    <Box><Stack direction="row" spacing={1} sx={{ alignItems: 'center', mb: 1 }}><Typography variant="h6">Selected source configuration</Typography><Chip size="small" label={`Point ${pointId}`} />{ci >= 0 && <Chip size="small" color={Number(row[ci]) === 1 ? 'success' : 'warning'} label={Number(row[ci]) === 1 ? 'Converged' : 'Non-converged'} />}</Stack><Stack direction="row" spacing={0.8} useFlexGap sx={{ flexWrap: 'wrap' }}>{sourceCols.map((column) => <Chip key={column} size="small" variant="outlined" label={`${sourceCoordinateLabel(column, amplitudeUnit)} = ${formatNumber(Number(row[table.columns.indexOf(column)]))}`} />)}</Stack></Box>
    {savedPoint && Object.keys(savedPoint.parameters).length > 0 && <><Divider /><Box><Typography variant="subtitle2" sx={{ mb: 0.8 }}>Device parameters</Typography><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.8 }}>Circuit parameters used for this Harmonic Balance point; they are not source-sweep coordinates.</Typography><Stack direction="row" spacing={0.8} useFlexGap sx={{ flexWrap: 'wrap' }}>{Object.entries(savedPoint.parameters).map(([name, value]) => <Chip key={name} size="small" variant="outlined" label={`${name} = ${formatNumber(Number(value))}`} />)}</Stack></Box></>}
    <Divider /><Box><Typography variant="subtitle2" sx={{ mb: 0.8 }}>Scalar metrics</Typography><Stack direction="row" spacing={0.8} useFlexGap sx={{ flexWrap: 'wrap' }}>{metrics.map((column) => <Chip key={column} size="small" variant="outlined" label={`${column} = ${formatNumber(Number(row[table.columns.indexOf(column)])) || 'unavailable'}`} />)}</Stack></Box>
    <Divider /><Box><Stack direction="row" spacing={1} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap' }}><Box><Typography variant="subtitle2">Retained arrays</Typography><Typography variant="caption" color="text.secondary">Selections persist when you click another configuration.</Typography></Box><FormControl size="small" sx={{ minWidth: 250, ml: { sm: 'auto' } }}><InputLabel>X vector</InputLabel><Select label="X vector" value={catalog.some((item) => item.key === xChoice) || xChoice === 'auto' ? xChoice : 'auto'} disabled={!catalog.length || Boolean(loadingKey)} onChange={(event) => void chooseXAxis(event.target.value)}><MenuItem value="auto">Automatic · frequency / index</MenuItem>{catalog.map((item) => <MenuItem key={item.key} value={item.key}>{item.quantityName === item.arrayName ? item.quantityName : `${item.quantityName} · ${item.arrayName}`} · {item.length.toLocaleString()} pts</MenuItem>)}</Select></FormControl></Stack>
      {!savedPoint?.quantities.length ? <Typography variant="body2" color="text.secondary" sx={{ mt: 0.7 }}>No user-selected arrays are catalogued for this point.</Typography> : <Stack spacing={0.8} sx={{ mt: 1 }}>{savedPoint.quantities.map((quantity) => <Paper key={quantity.name} variant="outlined" sx={{ p: 1 }}><Stack direction="row" spacing={0.8} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap' }}><Typography variant="body2" sx={{ fontWeight: 700 }}>{quantity.quantityName}</Typography>{quantity.arrays.map((array) => { const key = `${quantity.name}/${array.name}`; const selected = selectionRef.current.some((item) => item.key === key); const catalogItem = catalog.find((item) => item.key === key)!; return <Button key={array.name} size="small" variant={selected ? 'contained' : 'outlined'} disabled={Boolean(loadingKey)} onClick={() => selected ? removeTrace(key) : void addTrace(catalogItem)}>{array.name} · {array.length.toLocaleString()} pts · {selected ? 'Remove' : loadingKey === key ? 'Loading…' : 'Add to plot'}</Button> })}</Stack></Paper>)}</Stack>}
    </Box>{error && <Alert severity="warning">{error}</Alert>}
    {groups.map((group) => <Paper key={group.key} variant="outlined" sx={{ p: 1.5 }}><Stack direction="row" spacing={0.8} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap', mb: 1 }}>{group.traces.map((item) => <Stack key={item.key} direction="row" spacing={0.7} sx={{ alignItems: 'center' }}><Chip label={traceLabel(item.trace)} />{item.trace.magnitude && <FormControl size="small" sx={{ minWidth: 120 }}><InputLabel>View</InputLabel><Select label="View" value={item.component} onChange={(event) => { const component = event.target.value as TraceComponent; selectionRef.current = selectionRef.current.map((s) => s.key === item.key ? { ...s, component } : s); setTraces((current) => current.map((trace) => trace.key === item.key ? { ...trace, component } : trace)) }}><MenuItem value="magnitude">magnitude</MenuItem><MenuItem value="real">real</MenuItem><MenuItem value="imag">imag</MenuItem><MenuItem value="phase">phase</MenuItem></Select></FormControl>}<Button size="small" onClick={() => removeTrace(item.key)}>Remove</Button></Stack>)}</Stack><LineChart height={330} xAxis={[{ data: group.x, label: group.xLabel, valueFormatter: (value: number | null) => formatNumber(value) }]} yAxis={[{ valueFormatter: (value: number | null) => formatNumber(value) }]} series={group.traces.map((item) => ({ data: traceValues(item), label: `${traceLabel(item.trace)}${item.component === 'values' ? '' : ` (${item.component})`}`, showMark: traceValues(item).length < 100, valueFormatter: (value: number | null) => formatNumber(value) }))} grid={{ horizontal: true }} /></Paper>)}
  </Stack></Paper>
}

function HarmonicBalanceRun({ run, unitControl, amplitudeUnit }: { run: RunResults; unitControl?: React.ReactNode; amplitudeUnit: SourceAmplitudeUnit }) {
  const table = run.nonlinear
  if (!table) return <Alert severity="info">This run does not contain a Harmonic Balance dataset.</Alert>
  const coordinates = sourceCoordinateColumns(table); const metrics = metricColumns(table); if (coordinates.length < 2 || !metrics.length) return <Alert severity="warning">The Harmonic Balance table does not contain enough source coordinates and scalar metrics.</Alert>
  const defaultX = coordinates.find((name) => /frequency$/i.test(name)) ?? coordinates[0]; const defaultY = coordinates.find((name) => /amplitude$/i.test(name) && name !== defaultX) ?? coordinates.find((name) => name !== defaultX) ?? coordinates[1]
  const [view, setView] = useState<HbView>('landscape'); const [metric, setMetric] = useState(metrics.includes('performance') ? 'performance' : metrics[0]); const [x, setX] = useState(defaultX); const [y, setY] = useState(defaultY); const [convergence, setConvergence] = useState<ConvergenceFilter>('all'); const [fixed, setFixed] = useState<Record<string, number>>({}); const [selectedPointId, setSelectedPointId] = useState<number | null>(null); const [showConfigurations, setShowConfigurations] = useState(false)
  const amplitudes = amplitudeColumns(table); const [responseAmplitude, setResponseAmplitude] = useState(amplitudes[0] ?? ''); const [responseFixed, setResponseFixed] = useState<Record<string, number>>({})
  useEffect(() => { const next: Record<string, number> = {}; coordinates.filter((column) => column !== x && column !== y).forEach((column) => { const options = columnValues(table, column); next[column] = options.includes(fixed[column]) ? fixed[column] : options[0] }); setFixed(next) }, [table, x, y])
  useEffect(() => { const next: Record<string, number> = {}; coordinates.filter((column) => column !== responseAmplitude).forEach((column) => { const options = columnValues(table, column); next[column] = options.includes(responseFixed[column]) ? responseFixed[column] : options[0] }); setResponseFixed(next) }, [table, responseAmplitude])
  const grid = useMemo(() => x !== y ? buildHbGrid(table, x, y, metric, fixed, convergence) : null, [table, x, y, metric, fixed, convergence])
  useEffect(() => { const ids = grid?.pointIds.flat().filter((id): id is number => id != null) ?? []; if (selectedPointId == null || !ids.includes(selectedPointId)) setSelectedPointId(ids[0] ?? null) }, [grid, selectedPointId])
  const fixedSummary = coordinates.filter((column) => column !== x && column !== y).map((column) => `${sourceCoordinateLabel(column, amplitudeUnit)}=${formatNumber(fixed[column])}`).join(', ')
  const responseRows = useMemo(() => { const ai = table.columns.indexOf(responseAmplitude); return responseAmplitude ? rowsAsNumbers(table).filter((row) => rowMatchesFixed(table, row, responseFixed) && convergenceMatches(table, row, convergence) && Number.isFinite(row[ai])).sort((a, b) => a[ai] - b[ai]) : [] }, [table, responseAmplitude, responseFixed, convergence])
  const ai = table.columns.indexOf(responseAmplitude); const pi = table.columns.indexOf('performance'); const di = table.columns.indexOf('delta_quantity')
  return <Stack spacing={1.5}>
    <Paper variant="outlined" sx={{ p: 1.25 }}><Stack direction="row" spacing={1.2} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap' }}><Button size="small" variant={view === 'landscape' ? 'contained' : 'outlined'} onClick={() => setView('landscape')}>Landscape</Button><Button size="small" variant={view === 'response' ? 'contained' : 'outlined'} onClick={() => setView('response')}>Amplitude response</Button><Chip sx={{ ml: { md: 'auto' } }} size="small" variant="outlined" color="success" label={`${table.rows.length.toLocaleString()} HB points`} /></Stack></Paper>
    <Paper variant="outlined" sx={{ p: 1.25 }}><Stack direction="row" spacing={1} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap' }}>
      {view === 'landscape' && <><FormControl size="small" sx={{ minWidth: 210 }}><InputLabel>Metric</InputLabel><Select label="Metric" value={metric} onChange={(event) => setMetric(event.target.value)}>{metrics.map((column) => <MenuItem key={column} value={column}>{column}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 160 }}><InputLabel>X axis</InputLabel><Select label="X axis" value={x} onChange={(event) => { const next = event.target.value; setX(next); if (next === y) setY(coordinates.find((column) => column !== next) ?? y) }}>{coordinates.map((column) => <MenuItem key={column} value={column}>{column}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 160 }}><InputLabel>Y axis</InputLabel><Select label="Y axis" value={y} onChange={(event) => setY(event.target.value)}>{coordinates.filter((column) => column !== x).map((column) => <MenuItem key={column} value={column}>{column}</MenuItem>)}</Select></FormControl>{coordinates.filter((column) => column !== x && column !== y).map((column) => <FormControl key={column} size="small" sx={{ minWidth: 180 }}><InputLabel>{column} fixed</InputLabel><Select label={`${column} fixed`} value={fixed[column] ?? ''} onChange={(event) => setFixed((current) => ({ ...current, [column]: Number(event.target.value) }))}>{columnValues(table, column).map((value) => <MenuItem key={value} value={value}>{formatNumber(value)}</MenuItem>)}</Select></FormControl>)}</>}
      {view === 'response' && <><FormControl size="small" sx={{ minWidth: 210 }}><InputLabel>Source amplitude</InputLabel><Select label="Source amplitude" value={responseAmplitude} onChange={(event) => setResponseAmplitude(event.target.value)}>{amplitudes.map((column) => <MenuItem key={column} value={column}>{column}</MenuItem>)}</Select></FormControl>{coordinates.filter((column) => column !== responseAmplitude).map((column) => <FormControl key={column} size="small" sx={{ minWidth: 180 }}><InputLabel>{column} fixed</InputLabel><Select label={`${column} fixed`} value={responseFixed[column] ?? ''} onChange={(event) => setResponseFixed((current) => ({ ...current, [column]: Number(event.target.value) }))}>{columnValues(table, column).map((value) => <MenuItem key={value} value={value}>{formatNumber(value)}</MenuItem>)}</Select></FormControl>)}</>}
      <Stack direction="row" spacing={1} sx={{ ml: { md: 'auto' }, alignItems: 'center' }}>
        <FormControl size="small" sx={{ minWidth: 175 }}><InputLabel>Convergence</InputLabel><Select label="Convergence" value={convergence} onChange={(event) => setConvergence(event.target.value as ConvergenceFilter)}><MenuItem value="all">All points</MenuItem><MenuItem value="converged">Converged</MenuItem><MenuItem value="nonconverged">Non-converged</MenuItem></Select></FormControl>
        {unitControl}
      </Stack>
    </Stack></Paper>
    {view === 'landscape' && <Stack spacing={1.2}>{grid && grid.x.length > 0 && grid.y.length > 0 ? <Paper variant="outlined" sx={{ p: 1.7 }}><Typography variant="h6">{metric}</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>{x} × {y} · Harmonic Balance dataset{fixedSummary ? ` · fixed: ${fixedSummary}` : ''}.</Typography><Box sx={{ minHeight: 390, display: 'flex', alignItems: 'center' }}><HeatmapGrid xLabels={grid.x.map(formatNumber)} yLabels={grid.y.map(formatNumber)} values={grid.values} valueLabel={metric} xAxisLabel={x} yAxisLabel={y} amplitudeUnit={amplitudeUnit} formatValue={formatNumber} onCellClick={(r, c) => { const id = grid.pointIds[r]?.[c]; if (id != null) setSelectedPointId(id) }} /></Box></Paper> : <Alert severity="info">No stored Harmonic Balance points match the selected slice and convergence filter.</Alert>}<HbPointInspector run={run} table={table} pointId={selectedPointId} amplitudeUnit={amplitudeUnit} /><Box><Button size="small" variant="text" onClick={() => setShowConfigurations((current) => !current)}>{showConfigurations ? 'Hide stored configurations' : 'Show stored configurations'}</Button>{showConfigurations && <Box sx={{ mt: 0.7 }}><StoredConfigurations table={table} pointId={selectedPointId} onSelect={setSelectedPointId} /></Box>}</Box></Stack>}
    {view === 'response' && <Stack spacing={1.2}>{!responseRows.length ? <Alert severity="info">No points match the selected amplitude-response slice.</Alert> : <>{pi >= 0 && <Paper variant="outlined" sx={{ p: 1.7 }}><Typography variant="h6">performance</Typography><LineChart height={340} xAxis={[{ data: responseRows.map((row) => row[ai]), label: sourceCoordinateLabel(responseAmplitude, amplitudeUnit), valueFormatter: (value: number | null) => formatNumber(value) }]} yAxis={[{ label: 'performance', valueFormatter: (value: number | null) => formatNumber(value) }]} series={[{ data: responseRows.map((row) => row[pi]), label: 'performance', showMark: true, valueFormatter: (value: number | null) => formatNumber(value) }]} grid={{ horizontal: true }} /></Paper>}{di >= 0 && <Paper variant="outlined" sx={{ p: 1.7 }}><Typography variant="h6">delta_quantity</Typography><LineChart height={340} xAxis={[{ data: responseRows.map((row) => row[ai]), label: sourceCoordinateLabel(responseAmplitude, amplitudeUnit), valueFormatter: (value: number | null) => formatNumber(value) }]} yAxis={[{ label: 'delta_quantity', valueFormatter: (value: number | null) => formatNumber(value) }]} series={[{ data: responseRows.map((row) => row[di]), label: 'delta_quantity', showMark: true, valueFormatter: (value: number | null) => formatNumber(value) }]} grid={{ horizontal: true }} /></Paper>}</>}</Stack>}
  </Stack>
}

export function HarmonicBalanceResultsNormalized({ results, activeRunId, unitControl, amplitudeUnit = 'A' }: { results: ResultsBundle; activeRunId?: string | null; unitControl?: React.ReactNode; amplitudeUnit?: SourceAmplitudeUnit }) {
  const [runId, setRunId] = useState(results.runs[0]?.id ?? '')
  useEffect(() => { if (!results.runs.some((run) => run.id === runId)) setRunId(results.runs[0]?.id ?? '') }, [results, runId])
  const run = results.runs.find((item) => item.id === runId) ?? results.runs[0]
  if (!run) return <Alert severity="info">The project contains no indexed runs yet.</Alert>
  return <Stack spacing={1.3}><Paper variant="outlined" sx={{ p: 1.2 }}><Stack direction="row" spacing={1} useFlexGap sx={{ alignItems: 'center', flexWrap: 'wrap' }}><FormControl size="small" sx={{ minWidth: 290 }}><InputLabel>Run</InputLabel><Select label="Run" value={run.id} onChange={(event) => setRunId(event.target.value)}>{results.runs.map((item) => <MenuItem key={item.id} value={item.id}>{item.id}{item.id === activeRunId ? ' · running' : ''}</MenuItem>)}</Select></FormControl><Chip size="small" color="success" variant="outlined" label="Stored JCO data" />{run.savedNonlinear && <Chip size="small" variant="outlined" label={`${run.savedNonlinear.points.length} retained-data points`} />}</Stack></Paper><HarmonicBalanceRun run={run} unitControl={unitControl} amplitudeUnit={amplitudeUnit} /></Stack>
}
